// @generated by kani-cli from fixture-gen.yaml — edit freely, but regenerate with `kani-cli generate` to reset.

use kani_shared::ast::{BlueprintBuilder, Expr, OffsetType};
use kani_shared::bindings::exports::kani::extension::manga_provider::Guest;
use kani_shared::host_abi::{extract, HttpRequest};
use kani_shared::{
    bindings, filter_list, to_shared_filters, types::ActiveFilter, wit_types, ExtensionMetadata,
    ExtensionResult, FilterState, MangaExtension,
};
use std::sync::OnceLock;
use wit_types::{Chapter, ChapterInfo, ChapterList, MangaInfo, MangaList, PreferenceSpec};

kani_shared::guest_alloc!();

pub struct FixtureGen {
    base_url: String,
}

impl Default for FixtureGen {
    fn default() -> Self {
        Self::new()
    }
}

impl FixtureGen {
    pub fn new() -> Self {
        Self {
            base_url: kani_shared::host_abi::prefs::get_str_or(
                "base_url",
                "https://fixture.invalid",
            ),
        }
    }

    pub fn metadata() -> ExtensionMetadata {
        ExtensionMetadata {
            id: "fixture-gen".to_string(),
            name: "FixtureGen".to_string(),
            version: "0.1.0".to_string(),
            base_url: "https://fixture.invalid".to_string(),
            language: "en".to_string(),
            nsfw: false,
            unrestricted_http: true,
            mihon_source_id: None,
            rate_limit: None,
            icon: None,
            languages: vec![],
            description: None,
            schema_version: 1_u32,
            min_kani_version: None,
            requires_capabilities: vec![],
            sections: vec![],
            scripts: std::collections::BTreeMap::new(),
            pre_request: None,
            on_status: std::collections::BTreeMap::new(),
            endpoint_pre_request: std::collections::BTreeMap::new(),
            endpoint_on_status: std::collections::BTreeMap::new(),
            cache: std::collections::BTreeMap::new(),
            dsl_schema_version: Some(kani_shared::ast::DSL_SCHEMA_VERSION),
        }
    }
}

impl MangaExtension for FixtureGen {
    fn name(&self) -> &str {
        "FixtureGen"
    }

    fn get_popular_manga(
        &self,
        page: i32,
        page_size: i32,
        filters: &[ActiveFilter],
    ) -> ExtensionResult<MangaList> {
        let req = HttpRequest::get(format!("{}/popular", self.base_url)).endpoint_id("popular");
        let bp = BlueprintBuilder::new(".item")
            .request(req)
            .field("id", Expr::self_ref().attr("data-id"))
            .field("title", Expr::self_ref().first(".title").text())
            .build();
        let rows = extract::html(None, &bp)?;
        Ok(kani_shared::unpack::unpack_manga_list(
            &rows,
            kani_shared::unpack::HasNextPage::Static(false),
            kani_shared::unpack::TotalPages::None,
            &[],
        ))
    }

    fn search_manga(
        &self,
        query: &str,
        page: i32,
        page_size: i32,
        filters: &[ActiveFilter],
    ) -> ExtensionResult<MangaList> {
        let mut req = HttpRequest::get(format!("{}/search", self.base_url))
            .endpoint_id("search")
            .query("q", query);

        let __filter_mapping: [(String, kani_shared::request::FilterMapping); 1] = [(
            "genre".to_string(),
            kani_shared::request::FilterMapping::Simple("genre".to_string()),
        )];
        let __filter_format: Option<kani_shared::request::FilterFormat> = None;
        for (k, v) in kani_shared::request::apply_filters(
            &__filter_mapping,
            __filter_format.as_ref(),
            filters,
        ) {
            req = req.query(k, v);
        }
        let bp = BlueprintBuilder::new(".item")
            .request(req)
            .field("id", Expr::self_ref().attr("data-id"))
            .field("title", Expr::self_ref().first(".title").text())
            .paginated(20, "page", OffsetType::PageNumber { start: 1 })
            .build();
        let rows = extract::paginated_html(page, page_size, &bp)?;
        Ok(kani_shared::unpack::unpack_manga_list(
            &rows,
            kani_shared::unpack::HasNextPage::FromScalar,
            kani_shared::unpack::TotalPages::None,
            &[],
        ))
    }

    fn get_manga_details(&self, manga_id: &str) -> ExtensionResult<MangaInfo> {
        let req = HttpRequest::get(format!("{}/manga/{}", self.base_url, manga_id))
            .endpoint_id("manga_details");
        let bp = BlueprintBuilder::new(".manga")
            .request(req)
            .field("artists", Expr::list(vec![]))
            .field("authors", Expr::list(vec![]))
            .field("status", Expr::lit("unknown"))
            .field("tags", Expr::list(vec![]))
            .field("title", Expr::self_ref().first("h1").text())
            .build();
        let rows = extract::html(None, &bp)?;
        kani_shared::unpack::unpack_manga_info(&rows, &[("id", manga_id)])
    }

    fn get_chapter_list(
        &self,
        manga_id: &str,
        _page: i32,
        _page_size: Option<i32>,
        _sort: Option<String>,
    ) -> ExtensionResult<ChapterList> {
        let req = HttpRequest::get(format!("{}/manga/{}/chapters", self.base_url, manga_id))
            .endpoint_id("chapter_list");
        let bp = BlueprintBuilder::new(".ch")
            .request(req)
            .field("id", Expr::self_ref().attr("data-id"))
            .field("language", Expr::lit("en"))
            .field("number", Expr::num(0.0))
            .field_opt("title", Expr::self_ref().first(".title").text())
            .build();
        let rows = extract::html(None, &bp)?;
        Ok(kani_shared::unpack::unpack_chapter_list(
            &rows,
            kani_shared::unpack::HasNextPage::Static(false),
            kani_shared::unpack::TotalPages::None,
            &[],
        ))
    }

    fn get_pages(&self, manga_id: &str, chapter_id: &str) -> ExtensionResult<Chapter> {
        let req = HttpRequest::get(format!(
            "{}/manga/{}/chapter/{}",
            self.base_url, manga_id, chapter_id
        ))
        .endpoint_id("pages");
        let bp = BlueprintBuilder::new(".page")
            .request(req)
            .field("index", Expr::index())
            .field("url", Expr::self_ref().attr("data-url"))
            .build();
        let rows = extract::html(None, &bp)?;
        Ok(kani_shared::unpack::unpack_pages(&rows, &[]))
    }

    fn get_chapter_sort_list(&self) -> ExtensionResult<Vec<wit_types::SortOption>> {
        Ok(vec![])
    }

    fn get_filter_list(&self) -> ExtensionResult<wit_types::FilterList> {
        Ok(filter_list! {
            "genre", "Genre", Multiselect, [("Action", "action"), ("Comedy", "comedy")]
        })
    }

    fn get_fetched_option_sets(&self) -> ExtensionResult<String> {
        Ok(r#"[]"#.to_string())
    }

    fn get_preferences(&self) -> ExtensionResult<Vec<PreferenceSpec>> {
        Ok(vec![])
    }
}

impl Guest for FixtureGen {
    fn get_metadata() -> Result<String, wit_types::ExtensionError> {
        Ok(kani_shared::serde_json::to_string(&FixtureGen::metadata())
            .expect("ExtensionMetadata serializes to JSON"))
    }

    fn get_popular_manga(
        page: i32,
        page_size: i32,
        filters: Vec<wit_types::ActiveFilter>,
    ) -> Result<MangaList, wit_types::ExtensionError> {
        let shared = to_shared_filters(filters);
        get_extension()
            .get_popular_manga(page, page_size, &shared)
            .map_err(|e| e.into_wit())
    }

    fn search_manga(
        query: String,
        page: i32,
        page_size: i32,
        filters: Vec<wit_types::ActiveFilter>,
    ) -> Result<MangaList, wit_types::ExtensionError> {
        let shared = to_shared_filters(filters);
        get_extension()
            .search_manga(&query, page, page_size, &shared)
            .map_err(|e| e.into_wit())
    }

    fn get_filter_list() -> Result<wit_types::FilterList, wit_types::ExtensionError> {
        get_extension().get_filter_list().map_err(|e| e.into_wit())
    }

    fn get_fetched_option_sets() -> Result<String, wit_types::ExtensionError> {
        get_extension()
            .get_fetched_option_sets()
            .map_err(|e| e.into_wit())
    }

    fn get_manga_details(manga_id: String) -> Result<MangaInfo, wit_types::ExtensionError> {
        get_extension()
            .get_manga_details(&manga_id)
            .map_err(|e| e.into_wit())
    }

    fn get_chapter_list(
        manga_id: String,
        page: i32,
        page_size: Option<i32>,
        sort: Option<String>,
    ) -> Result<ChapterList, wit_types::ExtensionError> {
        get_extension()
            .get_chapter_list(&manga_id, page, page_size, sort)
            .map_err(|e| e.into_wit())
    }

    async fn get_chapter_list_stream(
        manga_id: String,
        sort: Option<String>,
    ) -> kani_shared::StreamReader<Result<ChapterInfo, wit_types::ExtensionError>> {
        kani_shared::bridge_chapter_list_stream(get_extension(), manga_id, sort)
    }

    fn get_chapter_sort_list() -> Result<Vec<wit_types::SortOption>, wit_types::ExtensionError> {
        get_extension()
            .get_chapter_sort_list()
            .map_err(|e| e.into_wit())
    }

    fn get_pages(
        manga_id: String,
        chapter_id: String,
    ) -> Result<Chapter, wit_types::ExtensionError> {
        get_extension()
            .get_pages(&manga_id, &chapter_id)
            .map_err(|e| e.into_wit())
    }

    fn get_preferences() -> Result<Vec<PreferenceSpec>, wit_types::ExtensionError> {
        get_extension().get_preferences().map_err(|e| e.into_wit())
    }

    fn get_url(manga_id: String) -> Result<String, wit_types::ExtensionError> {
        get_extension().get_url(&manga_id).map_err(|e| e.into_wit())
    }
}

static EXTENSION: OnceLock<FixtureGen> = OnceLock::new();

fn get_extension() -> &'static FixtureGen {
    EXTENSION.get_or_init(FixtureGen::new)
}

bindings::export!(FixtureGen);
